'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'docs',new URL(req.url,'http://localhost').pathname);try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
server.listen(0,'127.0.0.1',async()=>{const doms=[];try{process.env.SITE_TEST_URL=`http://127.0.0.1:${server.address().port}/`;const {openPage,waitFor}=require('./audit_v25_jsdom');const real=JSON.parse(fs.readFileSync('docs/data/wom-cache.json'));const {dom,errors}=await openPage('gim.html',{priceData:{13263:{high:30000000,low:30000000},20997:{high:1000000000,low:1000000000}}});doms.push(dom);const w=dom.window,d=w.document;await waitFor(()=>d.querySelector('[data-mast-weekly-player]')?.textContent==='Lijpste','weekly leader');await waitFor(()=>d.querySelector('.mast-value-pie'),'priced value pie');assert.equal(d.querySelectorAll('.mast-status>.mast-stat').length,6);assert.equal(d.querySelector('[data-mast-weekly-xp]').textContent,'+6,948,043 XP');assert(d.querySelector('[data-mast-weekly-sub]').textContent.includes('Last 7 days'));assert(d.querySelector('[data-mast-weekly-sub]').title.includes('25 Sept 2026'));assert(!d.querySelector('.mast-value-legend'));assert(d.querySelector('.mast-value-pie').getAttribute('aria-label').includes('Lijpste'));assert(!d.querySelector('.mobile-menu-toggle'));
 const update=doc=>w.dispatchEvent(new w.CustomEvent('ug:data-updated',{detail:{key:'ug-v20-wom-cache',document:doc}}));
 let fixture=structuredClone(real);fixture.gains.week['lompste'].data.skills.overall.experience.gained=10000000;update(fixture);assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'Lompste');assert.equal(d.querySelector('[data-mast-weekly-xp]').textContent,'+10,000,000 XP');
 // Header summaries always cover all five accounts, independently of page/date filters.
 w.UGV21.saveMemberSelection(new Set(['dikste']));assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'Lompste');d.querySelector('[data-gim-tab="categories"]').click();assert.equal(d.querySelector('[data-mast-weekly-xp]').textContent,'+10,000,000 XP');
 fixture.gains.week['dikste'].data.skills.overall.experience.gained=10000000;update(fixture);assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'Dikste & Lompste');
 fixture=structuredClone(real);for(const row of Object.values(fixture.gains.week))row.data.skills.overall.experience.gained=0;update(fixture);assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'No XP gained');assert.equal(d.querySelector('[data-mast-weekly-xp]').textContent,'+0 XP');
 fixture={profiles:{},snapshots:{},gains:{}};update(fixture);assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'Weekly gains unavailable');assert.equal(d.querySelector('[data-mast-weekly-xp]').textContent,'—');
 fixture=structuredClone(real);fixture.gains.week['lijpste'].data.skills.overall.experience.gained=null;fixture.snapshots['lijpste']=[];update(fixture);assert.equal(d.querySelector('[data-mast-weekly-player]').textContent,'Dikste');assert(d.querySelector('[data-mast-weekly-sub]').textContent.includes('4/5 accounts'));
 fixture=structuredClone(real);delete fixture.gains.week;update(fixture);assert(d.querySelector('[data-mast-weekly-xp]').textContent.match(/^\+[\d,]+ XP$/));assert.equal(errors.length,0,errors.join('; '));console.log('Six overview cards, priced share label, weekly winner/exact XP, filter independence, updates, ties, zero, missing data and history fallback passed.');doms.forEach(x=>x.window.close());server.close();process.exit(0)}catch(e){console.error(e);doms.forEach(x=>x.window.close());server.close();process.exit(1)}});
