'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
// Own server lifetime so this check also runs in isolated execution environments.
const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'docs',new URL(req.url,'http://localhost').pathname);try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
function change(w,el,value){el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}))}
server.listen(0,'127.0.0.1',async()=>{process.env.SITE_TEST_URL=`http://127.0.0.1:${server.address().port}/`;const {openPage,waitFor}=require('./audit_v25_jsdom');const doms=[];try{
 let {dom,errors}=await openPage('cumulative-xp.html');doms.push(dom);let w=dom.window,d=w.document;await waitFor(()=>d.querySelectorAll('#cumulativeTable tbody tr').length===24,'cumulative skill rows');
 const model=require('../docs/assets/cumulative-xp-model'),real=require('../docs/data/wom-cache.json');assert(d.querySelector('#cumulativeSummary').textContent.includes(model.aggregate(real,Object.keys(real.profiles)).xp.toLocaleString('en-GB')));assert(d.querySelector('#cumulativePie svg'));assert.equal(d.querySelectorAll('#cumulativeContributions tbody tr').length,5);assert(d.querySelector('#nav-levels a[href="cumulative-xp.html"]'));assert(!d.querySelector('#nav-record a[href="cumulative-xp.html"]'));assert(d.querySelector('#historyLocalNav').textContent.includes('Levels'));assert(d.querySelector('#historyLocalNav a[href="cumulative-xp.html"]'));
 d.querySelector('[data-xp-view="pool"]').click();assert(!d.querySelector('#cumulativePool').hidden);assert(d.querySelector('#cumulativeTableCard').hidden);assert(d.querySelector('#cumulativePool').textContent.includes('144'));d.querySelector('[data-xp-view="account"]').click();
 for(const el of d.querySelectorAll('#cumulativeMembers input'))if(el.value!=='dikste'){el.checked=false;el.dispatchEvent(new w.Event('change',{bubbles:true}))}
 assert.equal(d.querySelectorAll('#cumulativeContributions tbody tr').length,1);assert(d.querySelector('#cumulativeContributions').textContent.includes('100.00%'));
 d.querySelector('#cumulativeClearSkills').click();assert(d.querySelector('#cumulativeSummary').textContent.includes('Select at least one skill'));const attack=d.querySelector('#cumulativeSkills input[value="attack"]');attack.checked=true;attack.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelectorAll('#cumulativeTable tbody tr').length,1);assert(d.querySelector('#cumulativeSummary').textContent.includes(real.profiles.dikste.latestSnapshot.data.skills.attack.experience.toLocaleString('en-GB')));assert.equal(errors.length,0,errors.join('; '));
 const temple=JSON.parse(fs.readFileSync('docs/data/temple-clog.json'));const values={'dikste':2,'big dog aura':1,'lijpste':0,'poep aura':0,'lompste':0};function tweak(n,count){if(!n||typeof n!=='object')return;if(+n.id===13274)n.count=count;for(const v of Object.values(n))if(v&&typeof v==='object')tweak(v,count)}for(const [key,count]of Object.entries(values))tweak(temple.players[key],count);
 ({dom,errors}=await openPage('gim.html',{savedTemple:temple}));doms.push(dom);w=dom.window;d=w.document;await waitFor(()=>d.querySelector('#clogOwnershipRules'),'ownership panel');assert(!d.querySelector('#gimKpis'));assert(!d.querySelector('#gimMembers'));assert(!d.querySelector('#fiveStandingTable'));assert.equal(d.querySelector('main > section h2').textContent,'Collection Log Advanced');assert(!d.querySelector('.collection-shell > .section-head .data-actions'));assert(!d.querySelector('.collection-shell > .section-head a'));assert(d.querySelector('#nav-logs a[href="clog-beta.html"]'));assert(d.querySelector('#nav-logs a[href="rng.html"]'));for(const id of ['clogContribution','clogOverlap','clogValue','clogCategories','recentDrops'])assert.equal(d.querySelector('#'+id).children.length,0,'Unselected view rendered: '+id);assert.equal(d.querySelectorAll('[data-gim-panel]:not([hidden])').length,1);const panel=d.querySelector('#clogOwnershipRules');assert.equal(panel.tagName,'DETAILS');assert(!panel.hidden);panel.open=true;
 const input=d.querySelector('#clogSearch');input.value='Bludgeon spine';input.dispatchEvent(new w.Event('input',{bubbles:true}));const choose=(key,value)=>{const el=d.querySelector(`[data-ownership-member="${key}"]`);el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}))};const keys=Object.keys(values);for(let mask=0;mask<32;mask++){for(let i=0;i<keys.length;i++)choose(keys[i],mask&(1<<i)?'has':'missing');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,mask===3?1:0,'Ownership pattern '+mask)}d.querySelector('#clogClearRules').click();choose('dikste','has');choose('lijpste','missing');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,1);assert(d.querySelector('#clogActiveRules').textContent.includes('Lijpste: missing'));
 choose('lijpste','has');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,0);choose('lijpste','missing');choose('dikste','dupes');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,1);change(w,d.querySelector('[data-ownership-bound="minOwners"]'),'2');change(w,d.querySelector('[data-ownership-bound="maxOwners"]'),'2');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,1);change(w,d.querySelector('[data-ownership-bound="maxOwners"]'),'1');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,0);
 d.querySelector('#clogClearRules').click();assert.equal(d.querySelector('#clogSearch').value,'Bludgeon spine');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,1);change(w,d.querySelector('#clogStatus'),'obtained-any');choose('lijpste','missing');assert.equal(d.querySelectorAll('#clogItemTable tbody tr').length,1);d.querySelector('#clogResetFilters').click();assert.equal(d.querySelector('#clogSearch').value,'');assert.equal(d.querySelector('#clogStatus').value,'all');assert(d.querySelector('#clogRuleSummary').textContent.includes('No extra'));assert.equal(errors.length,0,errors.join('; '));
 for(const view of ['ownership','categories','recent','recovery','collection']){change(w,d.querySelector('#clogView'),view);assert.equal(d.querySelectorAll('[data-gim-panel]:not([hidden])').length,1);assert.equal(d.querySelector('[data-gim-panel]:not([hidden])').dataset.gimPanel,view)}assert.equal(d.querySelector('#clogOverlap').children.length,0,'Collapsed pair overlap rendered');assert.equal(d.querySelector('#clogValue').children.length,0,'Unselected value view rendered');console.log('Cumulative XP navigation, account/skill selection, pooled level, pie shares, and combined ownership filters passed.');doms.forEach(x=>x.window.close());server.close();process.exit(0);
}catch(e){console.error(e);doms.forEach(x=>x.window.close());server.close();process.exit(1)}});
