const assert=require('node:assert/strict');
const H=require('../docs/assets/history-model');
const snap=(date,skills={},bosses={})=>({createdAt:date,data:{skills,bosses}});
const skill=(xp,level,ehp)=>({experience:xp,level,ehp});
const boss=(kills,ehb)=>({kills,ehb});
const a=snap('2026-01-01',{fishing:skill(0,50,0),magic:skill(0,50,0)},{zulrah:boss(0,0),obor:boss(0,0)});
const b=snap('2026-02-01',{fishing:skill(100000,54,20),magic:skill(4000000,70,0)},{zulrah:boss(10,1),obor:boss(2,.1)});
const e=H.describe(H.interval(a,b));
assert.equal(e.type,'Fishing');assert.equal(e.kc,12);assert.equal(e.xp,4100000);assert.equal(e.levels,24);
assert(e.bossesRanked.some(x=>x.key==='obor'),'every boss is included, including those outside the old curated families');
const mixed=H.describe(H.interval(a,snap('2026-02-01',{fishing:skill(1000000,55,10)},{zulrah:boss(50,10)})));
assert.equal(mixed.kind,'mixed');assert(mixed.type.includes('Fishing')&&mixed.type.includes('Zulrah'));
const missing=H.interval(snap('2026-01-01',{}, {obor:boss(-1,0)}),snap('2026-02-01',{fishing:skill(2000000,80,20)},{obor:boss(500,10)}));
assert.equal(missing.xp,0);assert.equal(Object.keys(missing.bosses).length,0,'unknown baseline must not invent gains');
const c=snap('2026-01-15',{fishing:skill(30000,51,4)},{zulrah:boss(2,.1)});
const periods=H.eras([b,c,a]);assert.equal(periods.length,1);assert.equal(periods[0].skills.fishing.xp,100000);assert.equal(periods[0].bosses.zulrah.kc,10);
assert.equal(H.eras([a,snap('2026-04-01',b.data.skills,b.data.bosses)])[0].gaps,1);
const events=[51,52,53,54].map(level=>({date:123,key:'player',metric:'fishing',type:'level',level}));
events.push({date:124,key:'other',type:'drop'});events.sort(H.compareEvents);
assert.deepEqual(events.slice(1).map(e=>e.level),[54,53,52,51]);assert.equal(events[0].date,124);
console.log('Chronicle numerical ordering and comprehensive activity-era tests passed');
