'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('docs/assets/experimental-theme.js','utf8'),nav=fs.readFileSync('docs/assets/v21-nav.js','utf8'),key='ug:experimental:osrs-theme:v1';
function open(saved=false,denied=false){const dom=new JSDOM(fs.readFileSync('docs/experimental.html','utf8'),{url:'https://example.com/experimental.html',runScripts:'outside-only'}),w=dom.window;if(saved!==null)w.localStorage.setItem(key,saved?'on':'off');if(denied)Object.defineProperty(w,'localStorage',{get(){throw new Error('Blocked storage')}});Object.defineProperty(w.document,'readyState',{value:'interactive'});w.matchMedia=()=>({matches:true,addEventListener(){}});w.eval(nav);w.eval(source);return dom}
let fresh=open(null);assert(fresh.window.UGExperimentalTheme.enabled,'Old School is the fresh-visitor default');assert.equal(fresh.window.document.querySelector('[data-theme-choice][data-selected="true"]').textContent,'Old School');fresh.window.document.querySelector('#osrsThemeSwitch').click();assert.equal(fresh.window.localStorage.getItem(key),'off','Modern choice is saved');fresh.window.close();
let dom=open(),w=dom.window,d=w.document;
assert(!d.documentElement.hasAttribute('data-theme'));assert(!d.querySelector('#osrsThemeStyles'));assert(!d.querySelector('[data-osrs-nav]'));assert.equal(d.querySelector('[data-osrs-theme-switch]').getAttribute('aria-checked'),'false');assert(d.querySelector('#nav-other a[href="experimental.html"] .nav-badge'));assert(!d.querySelector('#nav-record a[href="group-chemistry.html"]'));assert(d.querySelector('#nav-levels a[href="cumulative-xp.html"]'));assert(!d.querySelector('#nav-record a[href="nemesis-beta.html"]'));assert(!d.querySelector('#nav-record a[href="nemesis.html"]'));
w.localStorage.setItem('ug:members','keep');const originalNav=d.querySelector('.nav-inner'),originalMain=d.querySelector('main');
const toggle=d.querySelector('[data-osrs-theme-switch]');toggle.click();
assert.equal(w.localStorage.getItem(key),'on');assert.equal(d.documentElement.dataset.theme,'osrs');assert(d.querySelector('#osrsThemeStyles'));assert.equal(d.querySelectorAll('.osrs-menu-box').length,4);const statsBox=[...d.querySelectorAll('.osrs-menu-box')].find(box=>box.querySelector('h2').textContent==='Stats');assert(statsBox.querySelector('a[href="cumulative-xp.html"]'));assert(!d.querySelector('[data-osrs-nav] a[href="nemesis-beta.html"]'));assert(d.querySelector('.experimental-card a[href="nemesis.html"]'));assert(!d.querySelector('.experimental-card a[href="cumulative-xp.html"]'));assert(d.querySelector('.osrs-overview').textContent.includes('Overview'));assert.equal(d.querySelectorAll('[data-osrs-banner]').length,1);assert.equal(d.querySelectorAll('[data-osrs-nav]').length,1);assert.equal(d.querySelectorAll('.osrs-menu-link').length,d.querySelectorAll('.nav-inner .nav-link').length);assert.equal(w.localStorage.getItem('ug:members'),'keep');
const featurePages=['gim.html','hypothetical.html','rng.html','goals.html','history.html','cumulative-xp.html','kc-comparison.html'],featureSources=[];
for(const page of featurePages){const image=d.querySelector('[data-osrs-nav] a[href="'+page+'"] img');assert(image.classList.contains('osrs-feature-icon'));assert.equal(image.width,24);assert.equal(image.height,24);const file=image.getAttribute('src');assert(fs.existsSync('docs/'+file));featureSources.push(file)}assert.equal(new Set(featureSources).size,7,'each feature has a distinct icon');
w.UGExperimentalTheme.setEnabled(true);assert.equal(d.querySelectorAll('#osrsThemeStyles').length,1);assert.equal(d.querySelectorAll('[data-osrs-nav]').length,1);
toggle.click();assert(!d.querySelector('#osrsThemeStyles'));assert(!d.documentElement.hasAttribute('data-theme'));assert(!d.querySelector('[data-osrs-banner]'));assert(!d.querySelector('[data-osrs-nav]'));assert.equal(d.querySelector('.nav-inner'),originalNav);assert.equal(d.querySelector('main'),originalMain);assert.equal(w.localStorage.getItem(key),'off');assert.equal(w.localStorage.getItem('ug:members'),'keep');
w.localStorage.setItem(key,'on');w.dispatchEvent(new w.StorageEvent('storage',{key,newValue:'on'}));assert(w.UGExperimentalTheme.enabled);assert.equal(toggle.getAttribute('aria-checked'),'true');w.localStorage.clear();w.dispatchEvent(new w.StorageEvent('storage',{key:null}));assert(w.UGExperimentalTheme.enabled);assert.equal(toggle.getAttribute('aria-checked'),'true');dom.window.close();
dom=open(true);w=dom.window;assert.equal(w.document.documentElement.dataset.theme,'osrs');assert.equal(w.document.querySelector('[data-osrs-theme-switch]').getAttribute('aria-checked'),'true');dom.window.close();
dom=open(false,true);w=dom.window;assert(w.UGExperimentalTheme.enabled);w.UGExperimentalTheme.setEnabled(true);assert(w.UGExperimentalTheme.enabled);assert(w.document.querySelector('[data-osrs-theme-status]').textContent.includes('cannot save'));w.UGExperimentalTheme.setEnabled(false);assert(!w.document.querySelector('#osrsThemeStyles'));dom.window.close();
for(const file of fs.readdirSync('docs').filter(f=>f.endsWith('.html'))){const text=fs.readFileSync('docs/'+file,'utf8');if(!text.includes('assets/v21-nav.js'))continue;assert(text.includes('<script src="assets/experimental-theme.js?v=9"></script></head>'),file+': early optional theme bootstrap');assert.equal((text.match(/id="osrsThemeSwitch"/g)||[]).length,1,file+': one toggle');assert(text.indexOf('class="theme-toolbar"')<text.indexOf('class="mast"'),file+': toggle at top');assert(text.includes('role="switch" aria-checked="true"'));assert(!text.includes('href="assets/osrs-theme.css'),file+': theme CSS must stay lazy');assert(!text.includes('src="img/osrs-theme/'),file+': no theme imagery before opt-in')}
const css=fs.readFileSync('docs/assets/osrs-theme.css','utf8'),assets=JSON.parse(fs.readFileSync('docs/img/osrs-theme/sources.json'));
for(const asset of assets.assets)assert(fs.existsSync('docs/img/osrs-theme/'+asset.file),asset.file);
for(const match of css.matchAll(/url\('([^']+)'\)/g))assert(fs.existsSync('docs/assets/'+match[1]),match[1]);
console.log('Experimental theme: Old School default, persistent Modern choice, lazy assets, repeated toggles, exact DOM restoration, persistent and cross-tab preference, blocked storage fallback and resource paths passed.');
